### ISSUE TITLE
afterAttached() is not called in custom element

### ISSUE THREAD

**Issue by MT-PL-SWF-Dev** [aurelia-ui-toolkits/aurelia-after-attached-plugin#1]
When I try to use this plugin for custom element it is not called.

JS:
`export class MyElement {`
`attached(){`
`console.log("Called");`
`}`
`afterAttached(){`
`console.log("Not called");`
`}`
`}`

HTML:
`<my-element></my-element>`

**Comment by JeroenVinke** [comment]
Hey @MT-PL-SWF-Dev, 

This should be fixed now. Let me know if this is not the case

**Comment by MT-PL-SWF-Dev** [comment]
Seems to work, thank you! The only thing I have noticed for now is that with custom element with noView decorator doesn't raise this event. I understand it's kind of expected in some way, because you are using View prototype. Still attached is run on noView elements

**Comment by JeroenVinke** [comment]
@MT-PL-SWF-Dev should be good now

**Comment by MT-PL-SWF-Dev** [comment]
Sorry for long time without anwser, I was on vacation :)
@JeroenVinke Awesome job, it works like charm! Thank you :)

**Comment by JeroenVinke** [comment]
Excellent :+1: thanks for the update
